# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: salary.proto

require 'google/protobuf'

require 'google/protobuf/empty_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("salary.proto", :syntax => :proto3) do
    add_message "salary.GetSalaryRequest" do
      optional :user_id, :int64, 1
    end
    add_message "salary.GetSalaryResponse" do
      optional :salary, :message, 1, "salary.Salary"
    end
    add_message "salary.ListSalariesRequest" do
      optional :company_id, :int64, 1
    end
    add_message "salary.ListSalariesResponse" do
      repeated :salaries, :message, 1, "salary.Salary"
    end
    add_message "salary.DoubleBonusRequest" do
      optional :user_id, :int64, 1
    end
    add_message "salary.UpdateMonthlySalaryRequest" do
      optional :user_id, :int64, 1
      optional :monthly, :int64, 2
    end
    add_message "salary.Salary" do
      optional :monthly, :int64, 1
      optional :bonus, :int64, 2
      optional :user_id, :int64, 3
    end
    add_message "salary.ValidationError" do
      optional :path, :string, 2
      optional :type, :string, 3
      optional :meta, :string, 4
      optional :full_message, :string, 1
    end
  end
end

module SalaryPb
  GetSalaryRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("salary.GetSalaryRequest").msgclass
  GetSalaryResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("salary.GetSalaryResponse").msgclass
  ListSalariesRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("salary.ListSalariesRequest").msgclass
  ListSalariesResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("salary.ListSalariesResponse").msgclass
  DoubleBonusRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("salary.DoubleBonusRequest").msgclass
  UpdateMonthlySalaryRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("salary.UpdateMonthlySalaryRequest").msgclass
  Salary = Google::Protobuf::DescriptorPool.generated_pool.lookup("salary.Salary").msgclass
  ValidationError = Google::Protobuf::DescriptorPool.generated_pool.lookup("salary.ValidationError").msgclass
end
