# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: salary.proto for package 'salary'

require 'grpc'
require 'salary_pb'

module Salary
  module SalaryService
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'salary.SalaryService'

      rpc :GetSalary, GetSalaryRequest, GetSalaryResponse
      rpc :ListSalaries, ListSalariesRequest, ListSalariesResponse
      rpc :DoubleBonus, DoubleBonusRequest, Google::Protobuf::Empty
      rpc :UpdateMonthlySalary, UpdateMonthlySalaryRequest, Google::Protobuf::Empty
    end

    Stub = Service.rpc_stub_class
  end
end
